name: gym_track
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  # State
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1

  # UI
  lottie: ^3.3.2

  # Network
  dio: ^5.9.0

  # Firebase
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0

  # Utils
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7

  # Core
  
  flutter:
    sdk: flutter
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
